[package]
name = "pad-station"
version = "0.1.0"
authors = ["Siddharth Iyer <mail@yeahsid.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dioxus = { version = "0.5", features = ["web", "router"] }

# Debug
dioxus-logger = "0.5.1"
serde = { version = "1.0.210", features = ["derive"] }
wasm-bindgen = "0.2.93"
wasm-bindgen-futures = "0.4.43"
web-sys = "0.3.70"
reqwest = "0.12.7"
tokio = "1.40.0"
js-sys = "0.3.70"
dioxus-web = "0.5.6"
